---
apiVersion: v1
kind: ConfigMap
metadata:
  name: example-workload-1
  labels:
    app: anvil-test
    role: example-workload-1
data:
  workload-script.sh: |
    #!/bin/bash

    # do some tasks
    for i in {0..10}
    do
      echo "Writing task ${i} to file..."
      echo "count: ${i}" > /workspace/task-${i}.txt
      echo "Waiting 1 second..."
      sleep 1
    done

    # show the status
    ls -la /workspace

    # let logs know when we're done
    echo "Done!"

    # write the IPC flag file
    touch /workspace/done-doing-work
---
apiVersion: batch/v1
kind: Job
metadata:
  name: example-workload-1
  labels:
    app: anvil-test
    role: example-workload-1
spec:
  backoffLimit: 0
  template:
    spec:
      restartPolicy: Never
      containers:
      - name: some-heavy-task-that-takes-awhile
        image: library/bash
        command: ['bash', '/scripts/workload-script.sh']
        volumeMounts:
        - name: scripts
          mountPath: /scripts
        - name: workspace
          mountPath: /workspace
        - name: artifacts
          mountPath: /artifacts
      - name: anvil-wait
        image: kubesmith/kubesmith:0.1
        imagePullPolicy: Always
        command: ['kubesmith', 'anvil', 'wait', '--logtostderr', '-v', '2']
        env:
        - name: S3_HOST
          value: "minio.default.svc"
        - name: S3_PORT
          value: "9000"
        - name: S3_BUCKET_NAME
          value: "anvil-example"
        - name: S3_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              name: anvil-example
              key: minio-access-key
        - name: S3_SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: anvil-example
              key: minio-secret-key
        - name: S3_USE_SSL
          value: "false"
        - name: ARCHIVE_FILE_NAME
          value: "example-workload-1.tar.gz"
        - name: ARCHIVE_FILE_PATH
          value: "/artifacts"
        - name: ARTIFACT_PATHS
          value: "/workspace/task-2*,/workspace/task-4*,/workspace/task-10*"
        - name: FLAG_FILE_PATH
          value: "/workspace/done-doing-work"
        volumeMounts:
        - name: workspace
          mountPath: /workspace
        - name: artifacts
          mountPath: /artifacts
      volumes:
      - name: scripts
        configMap:
          name: example-workload-1
      - name: workspace
        emptyDir: {}
      - name: artifacts
        emptyDir: {}
