---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: pipelines.kubesmith.io
  labels:
    component: kubesmith
spec:
  group: kubesmith.io
  versions:
  - name: v1
    served: true
    storage: true
  scope: Namespaced
  names:
    plural: pipelines
    singular: pipeline
    kind: Pipeline
    categories:
    - all
---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: forges.kubesmith.io
  labels:
    component: kubesmith
spec:
  group: kubesmith.io
  versions:
  - name: v1
    served: true
    storage: true
  scope: Namespaced
  names:
    plural: forges
    singular: forge
    kind: Forge
    categories:
    - all
---
apiVersion: v1
kind: Namespace
metadata:
  name: kubesmith
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: kubesmith
  namespace: kubesmith
  labels:
    component: kubesmith
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: kubesmith
  labels:
    component: kubesmith
subjects:
  - kind: ServiceAccount
    namespace: kubesmith
    name: kubesmith
roleRef:
  kind: ClusterRole
  name: cluster-admin
  apiGroup: rbac.authorization.k8s.io
