---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: pipelines.kubesmith.io
  labels:
    component: kubesmith
spec:
  group: kubesmith.io
  version: v1
  scope: Namespaced
  names:
    plural: pipelines
    kind: Pipeline
    categories:
    - all
  additionalPrinterColumns:
  - name: Phase
    type: string
    description: The current phase of the pipeline
    JSONPath: .status.phase
  - name: Stage
    type: integer
    description: The current stage of the pipeline
    JSONPath: .status.stageIndex
---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: pipelinestages.kubesmith.io
  labels:
    component: kubesmith
spec:
  group: kubesmith.io
  version: v1
  scope: Namespaced
  names:
    plural: pipelinestages
    kind: PipelineStage
    categories:
    - all
  additionalPrinterColumns:
  - name: Phase
    type: string
    description: The current phase of the pipeline
    JSONPath: .status.phase
---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: pipelinejobs.kubesmith.io
  labels:
    component: kubesmith
spec:
  group: kubesmith.io
  version: v1
  scope: Namespaced
  names:
    plural: pipelinejobs
    kind: PipelineJob
    categories:
    - all
  additionalPrinterColumns:
  - name: Phase
    type: string
    description: The current phase of the pipeline
    JSONPath: .status.phase
---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: forges.kubesmith.io
  labels:
    component: kubesmith
spec:
  group: kubesmith.io
  version: v1
  scope: Namespaced
  names:
    plural: forges
    kind: Forge
    categories:
    - all
---
apiVersion: v1
kind: Namespace
metadata:
  name: kubesmith
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: kubesmith
  namespace: kubesmith
  labels:
    component: kubesmith
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: kubesmith
  labels:
    component: kubesmith
subjects:
  - kind: ServiceAccount
    namespace: kubesmith
    name: kubesmith
roleRef:
  kind: ClusterRole
  name: cluster-admin
  apiGroup: rbac.authorization.k8s.io
