apiVersion: kubesmith.io/v1
kind: Pipeline
metadata:
  name: example
  namespace: kubesmith
spec:
  workspace:
    path: src/github.com/carldanley/test-repo

  environment:
  - MY_TEST_VAR=foobar

  templates:
  - name: default
    image: golang
  - name: new-release
    only:
    - tags

  stages:
  - lint
  - dependencies
  - build
  - dockerize
  - deploy

  jobs:
  - name: lint code
    stage: lint
    extends:
    - default
    commands:
    - go get -u github.com/golang/lint/golint
    - golint ./
    allowFailure: true

  - name: install dependencies
    stage: dependencies
    extends:
    - default
    - new-release
    commands:
    - curl https://glide.sh/get | sh
    - glide install

  - name: build for linux
    stage: build
    extends:
    - default
    - new-release
    environment:
    - CGO_ENABLED=0
    - GOOS=linux
    commands:
    - go build -a -installsuffix cgo -o test-repo-linux
    artifacts:
    - name: linux
      when: on-success
      paths:
      - test-repo-linux

  - name: build for darwin
    stage: build
    extends:
    - default
    - new-release
    environment:
    - CGO_ENABLED=0
    - GOOS=darwin
    commands:
    - go build -a -installsuffix cgo -o test-repo-darwin
    artifacts:
    - name: linux
      when: on-success
      paths:
      - test-repo-darwin

  - name: make production image
    stage: dockerize
    extends:
    - default
    - new-release
    commands:
    - ls -la

  - name: deploy to production
    stage: deploy
    extends:
    - new-release
    image: lachlanevenson/k8s-kubectl
    environment: []
    commands:
    - printenv KUBE_CONFIG | base64 -d > /kube.config
    - kubectl --kubeconfig=/kube.config apply -f ./k8s/test-repo
    secrets:
    - kube_config

# status:
#   stageIndex: 0
#   phase: Queued
#   startTime: 2018-11-04T01:00:00Z
#   endTime: null
#   stages:
#   - index: 1
#     jobs:
#     - index: 1
#       resource:
#         name: job-1
#         namespace: default
#       startTime: 2018-11-04T01:00:09Z
#       endTime: 2018-11-04T01:01:29Z
