apiVersion: kubesmith.io/v1
kind: Pipeline
metadata:
  name: simple-pipeline
  namespace: kubesmith
spec:
  workspace:
    path: /go/src/github.com/carldanley/dualshock
    repoURL: git@github.com:carldanley/dualshock4.git

  environment:
  - MY_TEST_VAR=foobar

  templates:
  - name: default
    image: golang

  stages:
  - first
  - second
  - third

  jobs:
  - name: do something super easy using the built in runner (keeps syntax simple)
    stage: first
    image: ubuntu
    runner:
    - ls -la

  - name: do something that requires more time
    stage: second
    extends:
    - default
    command: ["/bin/sh", "-x", "/kubesmith/scripts/my-script.sh"]
    configMapData:
      my-script.sh: |
        go get -u golang.org/x/lint/golint
        golint ./
    allowFailure: true

  - name: demonstrate multiple script calls from one configuration
    stage: third
    image: busybox
    command: ["/bin/sh", "-c"]
    args:
    - /bin/sh -x /kubesmith/scripts/first-script.sh;
      /bin/sh -x /kubesmith/scripts/second-script.sh;
      /bin/sh -x /kubesmith/scripts/third-script.sh;
    configMapData:
      first-script.sh: |
        echo "hello from first script\n"
      second-script.sh: |
        echo "hello from second script\n"
      third-script.sh: |
        echo "hello from third script\n"
