apiVersion: kubesmith.io/v1
kind: Pipeline
metadata:
  name: simple-pipeline
  namespace: kubesmith
spec:
  workspace:
    path: /go/src/github.com/carldanley/dualshock
    repoURL: git@github.com:carldanley/dualshock4.git

  environment:
  - MY_TEST_VAR=foobar

  templates:
  - name: default
    image: golang

  stages:
  - linting
  - testing

  jobs:
  - name: lint code
    stage: linting
    extends:
    - default
    command: ["/bin/sh", "-x", "/kubesmith/scripts/my-script.sh"]
    args: []
    configMapData:
      my-script.sh: |
        #!/bin/sh -x

        go get -u golang.org/x/lint/golint
        golint ./
    allowFailure: true

  - name: do something to test second stage
    stage: testing
    image: ubuntu
    runner:
    - ls -la
