apiVersion: kubesmith.io/v1
kind: Pipeline
metadata:
  name: simple-pipeline
  namespace: kubesmith
spec:
  workspace:
    path: /go/src/github.com/carldanley/dualshock
    repoURL: git@github.com:carldanley/dualshock4.git

  environment:
  - MY_TEST_VAR=foobar

  templates:
  - name: default
    image: golang

  stages:
  - linting
  - testing

  jobs:
  - name: lint code
    stage: linting
    extends:
    - default
    commands:
    - go get -u golang.org/x/lint/golint
    - golint ./
    allowFailure: true

  - name: do something to test second stage
    stage: testing
    image: ubuntu
    commands:
    - ls -la
